version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 725667370394.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t pos_nest -f ./dockerfile .
      - docker tag pos_nest:latest 725667370394.dkr.ecr.us-east-1.amazonaws.com/pos_nest:latest

  post_build:
    commands:
      - docker push 725667370394.dkr.ecr.us-east-1.amazonaws.com/pos_nest:latest
